apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-mylanta
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: api-mylanta
  template:
    metadata:
      labels:
        app: api-mylanta
    spec:
      containers:
      - image: gcr.io/heptio-images/ks-guestbook-demo:0.2
        name: api-mylanta
        ports:
        - containerPort: 80
